"""empty message

Revision ID: 3c201873e99f
Revises: 70a8eb0db477
Create Date: 2020-09-15 21:24:04.553934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c201873e99f'
down_revision = '70a8eb0db477'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('class', sa.Column('days', sa.String(), nullable=True))
    op.add_column('class', sa.Column('hours', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('class', 'hours')
    op.drop_column('class', 'days')
    # ### end Alembic commands ###
