"""empty message

Revision ID: 4a3024717260
Revises: 3c201873e99f
Create Date: 2020-09-16 00:09:30.168474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a3024717260'
down_revision = '3c201873e99f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'video', ['sequ_nb', 'class_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'video', type_='unique')
    # ### end Alembic commands ###
